-- 코드를 입력하세요
# SELECT C1.CART_ID
# FROM
# (SELECT CART_ID
# FROM CART_PRODUCTS 
# WHERE NAME = 'MILK'
# GROUP BY CART_ID) C1
# INNER JOIN
# (SELECT CART_ID
# FROM CART_PRODUCTS 
# WHERE NAME = 'YOGURT'
# GROUP BY CART_ID) C2 ON C1.CART_ID = C2.CART_ID
# ORDER BY C1.CART_ID;

-- DISTINCT를 HAVING절에도 적용 가능. 제품의 개수가 여러개인 쿼리 불가능하다는 단점
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('MILK', 'YOGURT')
GROUP BY CART_ID
HAVING COUNT(DISTINCT(NAME)) >= 2
ORDER BY CART_ID
