-- 코드를 입력하세요
SELECT C1.CART_ID
FROM
(SELECT CART_ID
FROM CART_PRODUCTS 
WHERE NAME = 'MILK'
GROUP BY CART_ID) C1
INNER JOIN
(SELECT CART_ID
FROM CART_PRODUCTS 
WHERE NAME = 'YOGURT'
GROUP BY CART_ID) C2 ON C1.CART_ID = C2.CART_ID
ORDER BY C1.CART_ID;
