-- JOIN을 무조건 ITEM_ID끼리 해야하는건 아니구나
# SELECT I1.ITEM_ID, I1.ITEM_NAME, I1.RARITY
# FROM ITEM_INFO I1
# LEFT JOIN ITEM_TREE I2 ON I1.ITEM_ID = I2.ITEM_ID
# WHERE I1.ITEM_ID NOT IN
# (SELECT DISTINCT(PARENT_ITEM_ID)
# FROM ITEM_TREE
# WHERE PARENT_ITEM_ID IS NOT NULL)
# ORDER BY I1.ITEM_ID DESC;

SELECT I1.ITEM_ID, I1.ITEM_NAME, I1.RARITY
FROM ITEM_INFO I1
LEFT JOIN ITEM_TREE I2 ON I1.ITEM_ID = I2.PARENT_ITEM_ID
WHERE PARENT_ITEM_ID IS NULL
ORDER BY I1.ITEM_ID DESC;
