-- 이전 문제에서 JOIN을 특이하게하는걸보고 어설프게 해서 얻어걸린 결과에 가까움
-- 다른 컬럼 JOIN 방식 익숙해질 것. COUNT는 NULL을 0으로 카운팅함
# SELECT PARENT_ID, COUNT(*) AS CNT
# FROM ECOLI_DATA
# GROUP BY PARENT_ID
# ;

SELECT E1.ID, COUNT(E2.ID) AS CHILD_COUNT
FROM ECOLI_DATA E1 
LEFT JOIN ECOLI_DATA E2 ON E1.ID = E2.PARENT_ID
GROUP BY E1.ID;

# SELECT *
# FROM ECOLI_DATA E1 
# LEFT JOIN ECOLI_DATA E2 ON E1.ID = E2.PARENT_ID
# ;