-- NTILE(4) OVER(ORDER BY SIZE_OF_COLONY) 처음 사용해봄. 
-- 만약 나누는 구간의 비율이 다르면 뭘 써야하지?
SELECT E1.ID,
CASE WHEN Q = 1 THEN 'LOW'
    WHEN Q = 2 THEN 'MEDIUM'
    WHEN Q = 3 THEN 'HIGH'
    ELSE 'CRITICAL' END AS COLONY_NAME
FROM ECOLI_DATA E1
LEFT JOIN 
(SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY) AS Q
FROM ECOLI_DATA) TB ON E1.ID = TB.ID
ORDER BY ID ASC ;