-- MID함수로 SUBSTRING 대체 가능, CONCAT_WS로 값 사이에 문자 넣기 가능
SELECT USER_ID,	NICKNAME, CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS 전체주소,
CONCAT_WS('-',MID(TLNO,1,3),MID(TLNO,4,4),MID(TLNO,8,4)) AS 전화번호
FROM USED_GOODS_BOARD U1
LEFT JOIN USED_GOODS_USER U2 ON U1.WRITER_ID = U2.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY USER_ID DESC;