-- 코드를 입력하세요
SELECT A1.ANIMAL_ID, A1.ANIMAL_TYPE, A1.NAME
FROM ANIMAL_INS A1 
INNER JOIN ANIMAL_OUTS A2 ON A1.ANIMAL_ID = A2.ANIMAL_ID
WHERE A1.SEX_UPON_INTAKE LIKE '%Intact%' AND 
(A2.SEX_UPON_OUTCOME LIKE '%Spayed%' OR A2.SEX_UPON_OUTCOME LIKE '%Neutered%')  ;