-- 코드를 입력하세요
SELECT R1.REST_ID, R1.REST_NAME, R1.FOOD_TYPE, R1.FAVORITES, R1.ADDRESS, R2.SCORE
FROM REST_INFO R1 
INNER JOIN
(SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW
WHERE REVIEW_SCORE IS NOT NULL
GROUP BY REST_ID
) R2
ON R1.REST_ID = R2.REST_ID
WHERE R1.ADDRESS LIKE '서울%'
ORDER BY R2.SCORE DESC, R1.FAVORITES DESC ;

# SELECT r.REST_ID
# , r.REST_NAME
# , r.FOOD_TYPE
# , r.FAVORITES
# , r.ADDRESS
# , ROUND(AVG(y.REVIEW_SCORE), 2) AS SCORE
# FROM REST_INFO AS r

# LEFT JOIN REST_REVIEW AS y ON r.REST_ID = y.REST_ID

# WHERE ADDRESS LIKE '서울%' AND REVIEW_SCORE IS NOT NULL

# GROUP BY REST_ID
# ORDER BY SCORE DESC, FAVORITES DESC