-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(DISTINCT U1.USER_ID) AS USERS
FROM USER_INFO U1
INNER JOIN ONLINE_SALE U2 ON U1.USER_ID = U2.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;

# SELECT u1.user_id, sales_date, gender
# FROM USER_INFO U1
# INNER JOIN ONLINE_SALE U2 ON U1.USER_ID = U2.USER_ID
# WHERE GENDER IS NOT NULL;

# SELECT USER_ID, SALES_DATE
# FROM ONLINE_SALE
# ORDER BY SALES_DATE