-- 당일 대여 당일 반납도 1일 사용임을 간과해서 +1을 안했엇음
-- 7일 이상인 조건을 WHERE로 하려면 SELECT에서 쓴 집계함수 AVG보다 WEHRE가 먼저 실행되어야 해서 
-- 이중 쿼리가 되는데 이걸 HAVING을 쓰면 WHERE를 제거하고 단일쿼리로 해결 가능 

SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

/* HAVING 안쓰고 WHERE 쓴 이중쿼리...
SELECT TB.CAR_ID, TB.AVERAGE_DURATION
FROM
(SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID) TB
WHERE TB.AVERAGE_DURATION >=7
ORDER BY TB.AVERAGE_DURATION DESC, TB.CAR_ID DESC; */