-- 특정 KEY로 LEFT JOIN하면 RIGHT TB에서 그 KEY가 NULL인 것들의 정보도 얻을 수 있음 
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID;