-- 코드를 입력하세요
# SELECT * FROM FOOD_PRODUCT;

# SELECT F1.PRODUCT_ID, F1.PRODUCT_NAME, (F2.AMOUNT*F1.PRICE) AS TOTAL_SALES
# FROM FOOD_PRODUCT F1
# INNER JOIN FOOD_ORDER F2 ON F1.PRODUCT_ID = F2.PRODUCT_ID
# WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
# ORDER BY TOTAL_SALES DESC, F1.PRODUCT_ID ASC;

SELECT F1.PRODUCT_ID, F1.PRODUCT_NAME, (F2.AMOUNT*F1.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT F1
INNER JOIN
(SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
FROM FOOD_ORDER
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID) F2
ON F1.PRODUCT_ID = F2.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, F1.PRODUCT_ID ASC;