-- WITH RECURSIVE 재귀함수, COUNT NULL 0으로 읽는것 활용 잘할 것

WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM CTE
    WHERE HOUR < 23
)

SELECT CTE.HOUR, COUNT(A1.ANIMAL_ID) AS COUNT 
FROM ANIMAL_OUTS A1
RIGHT JOIN CTE ON HOUR(A1.DATETIME) = CTE.HOUR
GROUP BY HOUR
ORDER BY HOUR ASC;

# SELECT *
# FROM ANIMAL_OUTS A1
# RIGHT JOIN CTE ON HOUR(A1.DATETIME) = CTE.HOUR
# ORDER BY HOUR ASC;