-- 집계함수와 GROUP BY, + HAVING. SUM은 숫자를, COUNT를 개수 세기
SELECT MCDP_CD AS 진료과코드, COUNT(MCDP_CD)AS 5월예약건수
FROM APPOINTMENT
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m') = '2022-05'
GROUP BY MCDP_CD
ORDER BY 5월예약건수 ASC, 진료과코드 ASC ;