SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME ASC ;

/* 틀린 이유는 시간 다른것까지 체크 안해서
SELECT TB.ANIMAL_ID, TB.NAME
FROM
(SELECT I.ANIMAL_ID, I.NAME,
DATE_FORMAT(I.DATETIME, '%Y_%m_%d') AS I_DATE,
DATE_FORMAT(O.DATETIME, '%Y_%m_%d') AS O_DATE
FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID) TB
WHERE TB.I_DATE > TB.O_DATE
ORDER BY TB.I_DATE ASC;
*/