-- 새로 만든 테이블과도 JOIN이 가능. 
-- 다중쿼리일때 실행 순서를 잘 생각해야 앨리어스 사용으로 인한 오류 줄일 수 있음
/* SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (- SIZE_OF_COLONY), ID
FROM ECOLI_DATA  */

SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV,E.ID
FROM ECOLI_DATA E LEFT JOIN
(SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)) TB ON YEAR(E.DIFFERENTIATION_DATE) = TB.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;


-- 분화된 연도별 가장 큰 대장균의 크기
-- 연도별, 가장 큰 --> GROUP BY YEAR, SELECT MAX(SIZE_OF_COLONY)