-- 코드를 작성해주세요
# SELECT F.ID, F.FISH_NAME, F.LENGTH
# FROM FISH_INFO F
# LEFT JOIN 
# (SELECT F1.FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
# FROM FISH_INFO F1
# LEFT JOIN FISH_NAME_INFO F2 ON F1.FISH_TYPE = F2.FISH_TYPE
# GROUP BY F1.FISH_TYPE) TB
# ON F.FISH_TYPE = TB.FISH_TYPE
# WHERE F.LENGTH = TB.MAX_LENGTH
# ORDER BY F.ID ASC
# ;


SELECT F1.ID, F2.FISH_NAME, F1.LENGTH
FROM FISH_INFO F1
LEFT JOIN FISH_NAME_INFO F2 ON F1.FISH_TYPE = F2.FISH_TYPE
WHERE (F1.FISH_TYPE, LENGTH) IN
(SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
 FROM FISH_INFO
GROUP BY FISH_TYPE)
ORDER BY F1.ID ASC
;