# -- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/',U1.BOARD_ID,'/',U2.FILE_ID,U2.FILE_NAME,U2.FILE_EXT ) AS FILE_PATH
FROM USED_GOODS_BOARD U1
LEFT JOIN USED_GOODS_FILE U2 ON U1.BOARD_ID = U2.BOARD_ID
WHERE VIEWS = 
(SELECT MAX(VIEWS) AS VIEWS
FROM USED_GOODS_BOARD);