-- NULL 처리하는 COALESCE 함수. AVG(COALESCE(LENGTH,10))
# SELECT *
# FROM FISH_INFO
# WHERE LENGTH >=
# (SELECT AVG(LENGTH) AS AVG_LENGTH
# FROM FISH_INFO
# GROUP BY FISH_TYPE)
# ;

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(COALESCE(LENGTH,10)) >= 33
ORDER BY FISH_TYPE ASC;