-- FLOOR 함수를 모르고 있었음, GROUP BY된 것에 여러 개의 컬럼값이 있어서 동시에 출력은 불가능하지만 COUNT로 개수를 세는 것이 가능함 **

SELECT FLOOR(PRICE/10000)*10000 AS PRICE_GROUP, COUNT(PRODUCT_CODE) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP ASC ;

/* SELECT PRICE_GROUP, COUNT(PRICE_GROUP) AS PRODUCTS
FROM(
SELECT CASE
    WHEN PRICE BETWEEN 0 AND 9999 THEN 0
    WHEN PRICE BETWEEN 10000 AND 19999 THEN 10000
    WHEN PRICE BETWEEN 20000 AND 29999 THEN 20000
    WHEN PRICE BETWEEN 30000 AND 39999 THEN 30000 
    ELSE NULL END AS PRICE_GROUP
FROM PRODUCT) TB
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP; */


-- PRODUCT TB에서 PR